### ISSUE TITLE
Can't resolve 'typeface-baloo-2'

### ISSUE THREAD

**Issue by philnind** [marscollective/gatsby-themes#42]
When trying to deploy your Link Free Repo i'm met with the following error...

`ModuleNotFoundError: Module not found: Error: Can't resolve 'typeface-baloo-2'   in '/opt/build/repo/node_modules/@marscollective/gatsby-theme-link-free/src/c  omponents'`

**Comment by cwks** [comment]
Hi! We updated both the theme and starter to solve this dependency issue. Could you please delete your repository and try again with a new deploy?

You can do so with the following link: https://app.netlify.com/start/deploy?repository=https://github.com/marscollective/link-free&stack=cms

I’ll keep this issue open while waiting for your confirmation. 😊

**Comment by philnind** [comment]
All fixed thanks guys!
