### ISSUE TITLE
Social links at the bottom

### ISSUE THREAD

**Issue by AlekseiAQ** [marscollective/gatsby-themes#95]
[Example: https://linktr.ee/garyvee](https://linktr.ee/garyvee)

Any plans on adding something like that?

**Comment by cwks** [comment]
Hi, @AlekseiAQ! Do you mean the icons?

**Comment by cwks** [comment]
My apologies, the link didn't load correctly the first time. Now I see the social media icons at the bottom.

@dsoaress has plans to refactor the project in Next.js next month, so we can definitely add this feature. I can't provide you with a date, though, but stay tuned for future updates! :)
