### ISSUE TITLE
Link blocks, separator or label

### ISSUE THREAD

**Issue by AlekseiAQ** [marscollective/gatsby-themes#96]
If we take a look at [Guardian Linktree](https://linktr.ee/guardian). There are a lot of links without any separation. It will be nice to have some kind of blocks, separators, or labels, for example, News, Opinions, Sports and etc. I see how I want to use it, I feel others might too. This feature could be useful and make the project stand out from the Linktree. 

Text or text and a line as a separator should work. Any plans on adding something like that?

**Comment by cwks** [comment]
Hi, @AlekseiAQ! Thanks for the suggestion. We never saw such a huuuge list of links, so it never crossed our minds to add this feature. Currently, our priority is to refactor this project in Next.js - and @dsoaress is way better at explaining the reasons for this than I am - but after that we can definitely add this and other features.

I'll close this issue for now, but it got added to our roadmap.
