### ISSUE TITLE
Blog post idea

### ISSUE THREAD

**Issue by AlekseiAQ** [marscollective/gatsby-themes#97]
It's more a question or blog post idea than a feature request. I'm not very familiar with Gatsbyjs and just a little with Netlify. How I can install/deploy this started as an endpoint on the existing website/Gatsbyjs website (`example.com/links`). Any link or idea where to start will be helpful. Thank you.

**Comment by cwks** [comment]
Hi, @AlekseiAQ! Linkfree was built to work with subdomains like `links.marscollective.co`. In this scenario, it works automagically, you just have to add this subdomain in Netlify and it should do the rest.

For something like `domain.com/links`, you have to build the project manually using your terminal of choice and upload the static files to your host. It was never intended to support this scheme as it would add a considerate amount of complexity to the project.

**Comment by AlekseiAQ** [comment]
Thank you, @cwks!
